# Użyj obrazu bazowego safarov/freeswitch
FROM signalwire/freeswitch-public-base:latest

# Instalacja niezbędnych pakietów
RUN apt-get update && \
    apt-get install -y 
RUN unixodbc \
    unixodbc-dev \
    odbcinst \
    libmariadb-dev \
    libodbc1 \
    mariadb-client

# Dodaj plik konfiguracyjny ODBC
COPY odbc.ini /etc/odbc.ini
COPY odbcinst.ini /etc/odbcinst.ini

# Konfiguracja FreeSWITCH do używania ODBC
COPY modules.conf.xml /usr/local/freeswitch/conf/autoload_configs/modules.conf.xml
COPY switch.conf.xml /usr/local/freeswitch/conf/autoload_configs/switch.conf.xml

# Oczyść niepotrzebne pliki
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Ustawienie zmiennych środowiskowych dla ODBC
ENV ODBCINI /etc/odbc.ini
ENV ODBCSYSINI /etc

# Expose the necessary ports
EXPOSE 5060 5061 5080 5081 5066 7443 10000-20000/udp

# Start FreeSWITCH
CMD ["freeswitch", "-nonat"]